# Classic style from ImThemes
alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [20.0, 20.0]
windowRounding = 20.0
windowBorderSize = 1.0
windowMinSize = [30.0, 30.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 3.0
childBorderSize = 5.0
popupRounding = 3.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 3.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 3.0
grabMinSize = 10.0
grabRounding = 3.0
tabRounding = 3.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(229, 229, 229, 1.0)"
TextDisabled = "rgba(153, 153, 153, 1.0)"
WindowBg = "rgba(0, 0, 0, 0.8500000238418579)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(28, 28, 35, 0.9200000166893005)"
Border = "rgba(127, 127, 127, 0.5)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(109, 109, 109, 0.3899999856948853)"
FrameBgHovered = "rgba(119, 119, 175, 0.4000000059604645)"
FrameBgActive = "rgba(107, 104, 163, 0.6899999976158142)"
TitleBg = "rgba(68, 68, 137, 0.8299999833106995)"
TitleBgActive = "rgba(81, 81, 160, 0.8700000047683716)"
TitleBgCollapsed = "rgba(102, 102, 204, 0.2000000029802322)"
MenuBarBg = "rgba(102, 102, 140, 0.800000011920929)"
ScrollbarBg = "rgba(51, 63, 76, 0.6000000238418579)"
ScrollbarGrab = "rgba(102, 102, 204, 0.300000011920929)"
ScrollbarGrabHovered = "rgba(102, 102, 204, 0.4000000059604645)"
ScrollbarGrabActive = "rgba(104, 99, 204, 0.6000000238418579)"
CheckMark = "rgba(66, 150, 250, 1.0)"
SliderGrab = "rgba(61, 133, 224, 1.0)"
SliderGrabActive = "rgba(66, 150, 250, 1.0)"
Button = "rgba(89, 102, 155, 0.6200000047683716)"
ButtonHovered = "rgba(102, 122, 181, 0.7900000214576721)"
ButtonActive = "rgba(117, 137, 204, 1.0)"
Header = "rgba(102, 102, 229, 0.449999988079071)"
HeaderHovered = "rgba(114, 114, 229, 0.800000011920929)"
HeaderActive = "rgba(135, 135, 221, 0.800000011920929)"
Separator = "rgba(127, 127, 127, 0.6000000238418579)"
SeparatorHovered = "rgba(153, 153, 178, 1.0)"
SeparatorActive = "rgba(178, 178, 229, 1.0)"
ResizeGrip = "rgba(255, 255, 255, 0.1000000014901161)"
ResizeGripHovered = "rgba(198, 209, 255, 0.6000000238418579)"
ResizeGripActive = "rgba(198, 209, 255, 0.8999999761581421)"
Tab = "rgba(85, 85, 174, 0.7860000133514404)"
TabHovered = "rgba(114, 114, 229, 0.800000011920929)"
TabActive = "rgba(103, 103, 185, 0.8420000076293945)"
TabUnfocused = "rgba(72, 72, 145, 0.8212000131607056)"
TabUnfocusedActive = "rgba(89, 89, 166, 0.8371999859809875)"
PlotLines = "rgba(255, 255, 255, 1.0)"
PlotLinesHovered = "rgba(229, 178, 0, 1.0)"
PlotHistogram = "rgba(229, 178, 0, 1.0)"
PlotHistogramHovered = "rgba(255, 153, 0, 1.0)"
TableHeaderBg = "rgba(68, 68, 96, 1.0)"
TableBorderStrong = "rgba(79, 79, 114, 1.0)"
TableBorderLight = "rgba(66, 66, 71, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.07000000029802322)"
TextSelectedBg = "rgba(0, 0, 255, 0.3499999940395355)"
DragDropTarget = "rgba(255, 255, 0, 0.8999999761581421)"
NavHighlight = "rgba(114, 114, 229, 0.800000011920929)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
ModalWindowDimBg = "rgba(51, 51, 51, 0.3499999940395355)"