# Fork of Moonlight style from ImThemes
alpha = 1.0
disabledAlpha = 1.0
windowPadding = [5.0, 5.0]
windowRounding = 0.0
windowBorderSize = 0.0
windowMinSize = [20.0, 17.0]
windowTitleAlign = [0.5, 0.5]
windowMenuButtonPosition = "Right"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [14.0, 2.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [4.300000190734863, 5.5]
itemInnerSpacing = [7.099999904632568, 1.799999952316284]
cellPadding = [14.0, 2.0]
indentSpacing = 0.0
columnsMinSpacing = 4.900000095367432
scrollbarSize = 11.60000038146973
scrollbarRounding = 0.0
grabMinSize = 18.0
grabRounding = 0.0
tabRounding = 0.0
tabBorderSize = 1.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Left"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(195, 145, 67, 1.0)"
WindowBg = "rgba(13, 13, 13, 1.0)"
ChildBg = "rgba(20, 20, 20, 1.0)"
PopupBg = "rgba(20, 22, 26, 1.0)"
Border = "rgba(195, 145, 67, 1.0)"
BorderShadow = "rgba(0, 0, 0, 1.0)"
FrameBg = "rgba(46, 46, 46, 1.0)"
FrameBgHovered = "rgba(40, 43, 49, 1.0)"
FrameBgActive = "rgba(69, 69, 69, 1.0)"
TitleBg = "rgba(12, 14, 18, 1.0)"
TitleBgActive = "rgba(0, 0, 0, 1.0)"
TitleBgCollapsed = "rgba(20, 22, 26, 1.0)"
MenuBarBg = "rgba(0, 0, 0, 1.0)"
ScrollbarBg = "rgba(12, 14, 18, 1.0)"
ScrollbarGrab = "rgba(30, 34, 38, 1.0)"
ScrollbarGrabHovered = "rgba(40, 43, 49, 1.0)"
ScrollbarGrabActive = "rgba(30, 34, 38, 1.0)"
CheckMark = "rgba(195, 145, 67, 1.0)"
SliderGrab = "rgba(195, 145, 67, 1.0)"
SliderGrabActive = "rgba(255, 203, 127, 1.0)"
Button = "rgba(80, 7, 0, 1.0)"
ButtonHovered = "rgba(169, 16, 0, 1.0)"
ButtonActive = "rgba(195, 145, 67, 1.0)"
Header = "rgba(116, 11, 0, 1.0)"
HeaderHovered = "rgba(169, 16, 0, 1.0)"
HeaderActive = "rgba(94, 94, 94, 1.0)"
Separator = "rgba(116, 11, 0, 1.0)"
SeparatorHovered = "rgba(169, 16, 0, 1.0)"
SeparatorActive = "rgba(40, 47, 64, 1.0)"
ResizeGrip = "rgba(37, 37, 37, 1.0)"
ResizeGripHovered = "rgba(248, 255, 127, 1.0)"
ResizeGripActive = "rgba(255, 255, 255, 1.0)"
Tab = "rgba(195, 145, 67, 1.0)"
TabHovered = "rgba(131, 131, 131, 1.0)"
TabActive = "rgba(67, 67, 67, 1.0)"
TabUnfocused = "rgba(113, 113, 114, 1.0)"
TabUnfocusedActive = "rgba(32, 70, 146, 1.0)"
PlotLines = "rgba(133, 153, 179, 1.0)"
PlotLinesHovered = "rgba(10, 250, 250, 1.0)"
PlotHistogram = "rgba(225, 203, 143, 1.0)"
PlotHistogramHovered = "rgba(244, 244, 244, 1.0)"
TableHeaderBg = "rgba(0, 85, 255, 1.0)"
TableBorderStrong = "rgba(0, 85, 255, 1.0)"
TableBorderLight = "rgba(255, 0, 0, 1.0)"
TableRowBg = "rgba(0, 128, 255, 1.0)"
TableRowBgAlt = "rgba(0, 85, 255, 1.0)"
TextSelectedBg = "rgba(239, 239, 239, 1.0)"
DragDropTarget = "rgba(127, 131, 255, 1.0)"
NavHighlight = "rgba(68, 74, 255, 1.0)"
NavWindowingHighlight = "rgba(127, 131, 255, 1.0)"
NavWindowingDimBg = "rgba(50, 45, 139, 0.501960813999176)"
ModalWindowDimBg = "rgba(50, 45, 139, 0.501960813999176)"