# EOP style from ImThemes
alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [8.0, 8.0]
windowRounding = 20.0
windowBorderSize = 1.0
windowMinSize = [30.0, 30.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 20.0
childBorderSize = 5.0
popupRounding = 20.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 20.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 20.0
grabMinSize = 10.0
grabRounding = 20.0
tabRounding = 20.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(127, 127, 127, 1.0)"
WindowBg = "rgba(15, 15, 15, 0.9399999976158142)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(20, 20, 20, 0.9399999976158142)"
Border = "rgba(109, 109, 127, 0.5)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(40, 73, 122, 0.5400000214576721)"
FrameBgHovered = "rgba(66, 150, 249, 0.4000000059604645)"
FrameBgActive = "rgba(66, 150, 249, 0.6700000166893005)"
TitleBg = "rgba(10, 10, 10, 1.0)"
TitleBgActive = "rgba(40, 73, 122, 1.0)"
TitleBgCollapsed = "rgba(0, 0, 0, 0.5099999904632568)"
MenuBarBg = "rgba(35, 35, 35, 1.0)"
ScrollbarBg = "rgba(5, 5, 5, 0.5299999713897705)"
ScrollbarGrab = "rgba(79, 79, 79, 1.0)"
ScrollbarGrabHovered = "rgba(104, 104, 104, 1.0)"
ScrollbarGrabActive = "rgba(130, 130, 130, 1.0)"
CheckMark = "rgba(66, 150, 250, 1.0)"
SliderGrab = "rgba(61, 133, 224, 1.0)"
SliderGrabActive = "rgba(66, 150, 250, 1.0)"
Button = "rgba(66, 150, 249, 0.4000000059604645)"
ButtonHovered = "rgba(66, 150, 249, 1.0)"
ButtonActive = "rgba(15, 135, 249, 1.0)"
Header = "rgba(66, 150, 249, 0.3100000023841858)"
HeaderHovered = "rgba(66, 150, 249, 0.800000011920929)"
HeaderActive = "rgba(66, 150, 249, 1.0)"
Separator = "rgba(109, 109, 127, 0.5)"
SeparatorHovered = "rgba(25, 102, 191, 0.7799999713897705)"
SeparatorActive = "rgba(25, 102, 191, 1.0)"
ResizeGrip = "rgba(66, 150, 249, 0.2000000029802322)"
ResizeGripHovered = "rgba(66, 150, 249, 0.6700000166893005)"
ResizeGripActive = "rgba(66, 150, 249, 0.949999988079071)"
Tab = "rgba(45, 89, 147, 0.8619999885559082)"
TabHovered = "rgba(66, 150, 249, 0.800000011920929)"
TabActive = "rgba(50, 104, 173, 1.0)"
TabUnfocused = "rgba(17, 26, 37, 0.9724000096321106)"
TabUnfocusedActive = "rgba(34, 66, 108, 1.0)"
PlotLines = "rgba(155, 155, 155, 1.0)"
PlotLinesHovered = "rgba(255, 109, 89, 1.0)"
PlotHistogram = "rgba(229, 178, 0, 1.0)"
PlotHistogramHovered = "rgba(255, 153, 0, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.05999999865889549)"
TextSelectedBg = "rgba(66, 150, 249, 0.3499999940395355)"
DragDropTarget = "rgba(255, 255, 0, 0.8999999761581421)"
NavHighlight = "rgba(66, 150, 249, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.699999988079071)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2000000029802322)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.3499999940395355)"