# Light style from ImThemes
alpha = 1.0
disabledAlpha = 0.6000000238418579
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 0.0
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 0.0
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(0, 0, 0, 1.0)"
TextDisabled = "rgba(153, 153, 153, 1.0)"
WindowBg = "rgba(239, 239, 239, 1.0)"
ChildBg = "rgba(0, 0, 0, 0.0)"
PopupBg = "rgba(255, 255, 255, 0.9800000190734863)"
Border = "rgba(0, 0, 0, 0.300000011920929)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(255, 255, 255, 1.0)"
FrameBgHovered = "rgba(66, 150, 249, 0.4000000059604645)"
FrameBgActive = "rgba(66, 150, 249, 0.6700000166893005)"
TitleBg = "rgba(244, 244, 244, 1.0)"
TitleBgActive = "rgba(209, 209, 209, 1.0)"
TitleBgCollapsed = "rgba(255, 255, 255, 0.5099999904632568)"
MenuBarBg = "rgba(219, 219, 219, 1.0)"
ScrollbarBg = "rgba(249, 249, 249, 0.5299999713897705)"
ScrollbarGrab = "rgba(175, 175, 175, 0.800000011920929)"
ScrollbarGrabHovered = "rgba(124, 124, 124, 0.800000011920929)"
ScrollbarGrabActive = "rgba(124, 124, 124, 1.0)"
CheckMark = "rgba(66, 150, 250, 1.0)"
SliderGrab = "rgba(61, 133, 224, 1.0)"
SliderGrabActive = "rgba(66, 150, 250, 1.0)"
Button = "rgba(66, 150, 249, 0.4000000059604645)"
ButtonHovered = "rgba(66, 150, 249, 1.0)"
ButtonActive = "rgba(15, 135, 249, 1.0)"
Header = "rgba(66, 150, 249, 0.3100000023841858)"
HeaderHovered = "rgba(66, 150, 249, 0.800000011920929)"
HeaderActive = "rgba(66, 150, 249, 1.0)"
Separator = "rgba(99, 99, 99, 0.6200000047683716)"
SeparatorHovered = "rgba(35, 112, 204, 0.7799999713897705)"
SeparatorActive = "rgba(35, 112, 204, 1.0)"
ResizeGrip = "rgba(89, 89, 89, 0.1700000017881393)"
ResizeGripHovered = "rgba(66, 150, 249, 0.6700000166893005)"
ResizeGripActive = "rgba(66, 150, 249, 0.949999988079071)"
Tab = "rgba(194, 203, 213, 0.9309999942779541)"
TabHovered = "rgba(66, 150, 249, 0.800000011920929)"
TabActive = "rgba(151, 185, 225, 1.0)"
TabUnfocused = "rgba(234, 236, 238, 0.9861999750137329)"
TabUnfocusedActive = "rgba(189, 209, 233, 1.0)"
PlotLines = "rgba(99, 99, 99, 1.0)"
PlotLinesHovered = "rgba(255, 109, 89, 1.0)"
PlotHistogram = "rgba(229, 178, 0, 1.0)"
PlotHistogramHovered = "rgba(255, 114, 0, 1.0)"
TableHeaderBg = "rgba(198, 221, 249, 1.0)"
TableBorderStrong = "rgba(145, 145, 163, 1.0)"
TableBorderLight = "rgba(173, 173, 188, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(76, 76, 76, 0.09000000357627869)"
TextSelectedBg = "rgba(66, 150, 249, 0.3499999940395355)"
DragDropTarget = "rgba(66, 150, 249, 0.949999988079071)"
NavHighlight = "rgba(66, 150, 249, 0.800000011920929)"
NavWindowingHighlight = "rgba(178, 178, 178, 0.699999988079071)"
NavWindowingDimBg = "rgba(51, 51, 51, 0.2000000029802322)"
ModalWindowDimBg = "rgba(51, 51, 51, 0.3499999940395355)"